dubbo:
  application:
    name:  ${APP_NAME:dubbo-springboot-demo-provider}
    qos-enable: true
    qos-accept-foreign-ip: true
  protocol:
    name: ${PROTOCOL_NAME:dubbo}
    port: ${PROTOCOL_PORT:20880}
  registry:
    address: ${REG_ADDRESS:kubernetes://10.6.176.50:6443?registry-type=service&duplicate=false&namespace=webstore-demo}