apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-springboot-demo-provider
  namespace: dubbo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-springboot-demo-provider
  template:
    metadata:
      labels:
        app: dubbo-springboot-demo-provider
    spec:
      containers:
        - name: server
          image: release-ci.daocloud.io/dmp/spring-dubbo3-provider:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: dubbo-port
              containerPort: 20880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: 22222
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 22222
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /startup
              port: 22222
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-springboot-demo-provider
  namespace: dubbo-demo
spec:
  selector:
    app: dubbo-springboot-demo-provider
  ports:
    - protocol: TCP
      port: 20880
      targetPort: 20880