server:
  port: 8080
dubbo:
  protocol:
    name: tri
  application:
    name: ${APP_NAME:dubbo-springboot-demo-consumer}
    qos-enable: false
  registry:
    address: ${REG_ADDRESS:N/A}
  consumer:
    mesh-enable: true